### PR TITLE
Add support for Facebook datetime type:

### PR DESCRIPTION
**Pull request by Natim**
@rtfeldman Is this something that you would accept to have as part as this lib?

```{
      "created_time": "2017-04-06T22:04:21+0000",
      "from": {
        "name": "Jay P Jeanne",
        "id": "126577551217199"
      },
      "id": "126577551217199_122842541590700",
      "message": "Hello",
      "permalink_url": "https://www.facebook.com/126577551217199/posts/122842541590700",
    }```

### CODE REVIEW

**Comment by Natim** [comment]
According to the wikipedia page linked in the readme or the W3C definition, it doesn't seems to be a valid [ISO-8601 date](https://www.w3.org/TR/NOTE-datetime), however [Facebook claim](https://chris.banes.me/2011/06/24/correctly-parsing-graph-api-event-times/) it is.

The Facebook documentation itself doesn't elaborate about their datetime format.

 I tried to update the parser to add a oneOf, but I wasn't successful.

It is up to you to decide if you want to cover that case and I obviously can't blame you to decide to follow the spec to the letter, just wanted to let you know that I encountered something that claimed to be an ISO8601 datetime and that it apparently wasn't supported by this lib.

**Comment by Natim** [comment]
https://twitter.com/Natim/status/1036926248356929536

**Comment by rtfeldman** [comment]
@natim yeah I want to stick to the canonical definition here - although worth noting the author of https://package.elm-lang.org/packages/jweir/elm-iso8601/latest might feel differently!

**Comment by Natim** [comment]
Yes right : https://github.com/jweir/elm-iso8601/blob/5.0.0/tests/Tests.elm#L45

**Pull request closed without merging**
