### PR TITLE
Accept dates with no ending Z

### LINKED ISSUE #12: Does not work for datetime string without time zone designator
Hello,

If I'm not mistaken `2018-09-06T00:00:00` should be a valid ISO8601 format.

I shamelessly copied and tweaked the Ellie example from @gyzerok. 
https://ellie-app.com/3jRZM4f34Hja1

thanks

### PR DESCRIPTION
**Pull request by FabienHenon**
Fixes #12

### CODE REVIEW

**Comment by andys8** [comment]
Why is CI currently failing? Something wrong with the setup?
https://travis-ci.org/rtfeldman/elm-iso8601-date-strings/builds/483949442?utm_source=github_status&utm_medium=notification

**Comment by rtfeldman** [comment]
Looks good, thanks @FabienHenon!

**Comment by rtfeldman** [comment]
Published as 1.1.3.

**Comment by andys8** [comment]
Thanks for the released version. This is nice, because it now supports the default format used by Java / Spring / Jackson.

**Pull request merged**
